In [1]:
import pandas as pd
import yfinance as yf
import numpy as np

In [2]:

# read the wiki page of CAC 40, the fourth table contains the ticker infomation
ticker_df=pd.read_html("https://en.wikipedia.org/wiki/CAC_40")[4]
ticker_df.head()

         Company              Sector        GICS Sub-Industry  Ticker
0    Air Liquide     Basic Materials         Industrial Gases   AI.PA
1         Airbus         Industrials      Aerospace & Defense  AIR.PA
2         Alstom         Industrials           Rail Transport  ALO.PA
3  ArcelorMittal     Basic Materials                    Steel   MT.AS
4            AXA  Financial Services  Life & Health Insurance   CS.PA

In [3]:
# get only tickers
ticker=ticker_df["Ticker"].to_list()
print(ticker)

['AI.PA', 'AIR.PA', 'ALO.PA', 'MT.AS', 'CS.PA', 'BNP.PA', 'EN.PA', 'CAP.PA', 'CA.PA', 'ACA.PA', 'BN.PA', 'DSY.PA', 'ENGI.PA', 'EL.PA', 'ERF.PA', 'RMS.PA', 'KER.PA', 'OR.PA', 'LR.PA', 'MC.PA', 'ML.PA', 'ORA.PA', 'RI.PA', 'PUB.PA', 'RNO.PA', 'SAF.PA', 'SGO.PA', 'SAN.PA', 'SU.PA', 'GLE.PA', 'STLA.PA', 'STM.PA', 'TEP.PA', 'HO.PA', 'TTE.PA', 'URW.AS', 'VIE.PA', 'DG.PA', 'VIV.PA', 'WLN.PA']

In [4]:
# The yfinance package can download all information about a company
# below we will get data of the CAC 40 since 2010. 
# "Adjusted close" is the closing price after adjustments for all applicable 
# splits and dividend distributions. 
df = yf.download(ticker,start="2010-01-01")['Adj Close']

[*********************100%***********************]  40 of 40 completed

In [5]:
df

,ACA.PA,AI.PA,AIR.PA,ALO.PA,BN.PA,BNP.PA,CA.PA,CAP.PA,CS.PA,DG.PA,...,SGO.PA,STLA.PA,STM.PA,SU.PA,TEP.PA,TTE.PA,URW.AS,VIE.PA,VIV.PA,WLN.PA
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,7.259818,35.152561,11.207963,39.503082,28.888611,29.751301,23.579290,25.837214,7.530560,25.167980,...,25.259136,NaN,3.983301,29.081608,18.972000,21.286238,68.601776,13.093348,10.692304,NaN
2010-01-05,7.370203,34.449509,11.171909,39.610428,28.637955,29.694126,24.137564,26.158728,7.656071,25.360018,...,25.139629,NaN,3.982687,28.940529,19.418640,21.311808,68.513412,13.194281,10.689806,NaN
2010-01-06,7.500398,34.237354,11.272055,39.848122,28.634613,29.740906,23.960718,26.677803,7.734514,25.709440,...,25.033035,NaN,4.029433,28.644238,19.176878,21.325748,69.109764,13.387738,10.574944,NaN
2010-01-07,7.503227,34.195751,11.384212,39.970802,28.574459,30.260670,23.690254,26.398897,7.647105,25.718878,...,24.961973,NaN,3.977766,28.587803,19.373568,21.362940,68.380905,13.544745,10.542482,NaN
2010-01-08,7.624931,34.303909,11.496372,40.752888,28.507616,30.977947,23.922579,26.511236,7.671760,26.084042,...,25.129936,NaN,3.963005,28.330322,19.529278,21.386179,68.402977,14.074646,10.417631,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-12,9.569000,136.199997,112.099998,23.760000,49.615002,52.680000,16.209999,171.899994,27.025000,97.379997,...,46.119999,13.770,36.500000,137.160004,223.500000,56.619999,50.799999,24.740000,8.912000,41.330002
2022-12-13,9.698000,138.199997,113.480003,24.240000,49.730000,53.630001,16.219999,174.699997,27.405001,97.449997,...,47.029999,13.802,37.750000,141.039993,224.899994,57.889999,52.700001,25.120001,8.936000,41.570000
2022-12-14,9.671000,138.160004,113.000000,23.980000,49.730000,53.509998,15.605000,172.350006,27.080000,95.480003,...,47.000000,13.890,37.224998,139.500000,226.500000,57.480000,53.090000,25.389999,8.928000,40.910000
2022-12-15,9.346000,134.080002,110.680000,23.240000,48.625000,51.669998,15.815000,165.149994,26.215000,93.930000,...,45.235001,13.538,35.410000,132.779999,218.300003,56.430000,51.880001,24.299999,8.714000,38.139999
2022-12-16,9.384000,132.759995,109.980003,22.820000,48.625000,52.540001,15.575000,159.449997,26.030001,92.389999,...,44.610001,13.364,34.939999,130.820007,213.600006,55.660000,49.419998,24.230000,8.670000,37.070000

In [7]:
# The NAN means the stocks are not exchange back then. So we need to exlude the NAN
# for now we will drop the cloumn with NaN.

df.dropna(axis=1)
df.shape

(3322, 40)

In [8]:
df

,ACA.PA,AI.PA,AIR.PA,ALO.PA,BN.PA,BNP.PA,CA.PA,CAP.PA,CS.PA,DG.PA,...,SGO.PA,STLA.PA,STM.PA,SU.PA,TEP.PA,TTE.PA,URW.AS,VIE.PA,VIV.PA,WLN.PA
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,7.259818,35.152561,11.207963,39.503082,28.888611,29.751301,23.579290,25.837214,7.530560,25.167980,...,25.259136,NaN,3.983301,29.081608,18.972000,21.286238,68.601776,13.093348,10.692304,NaN
2010-01-05,7.370203,34.449509,11.171909,39.610428,28.637955,29.694126,24.137564,26.158728,7.656071,25.360018,...,25.139629,NaN,3.982687,28.940529,19.418640,21.311808,68.513412,13.194281,10.689806,NaN
2010-01-06,7.500398,34.237354,11.272055,39.848122,28.634613,29.740906,23.960718,26.677803,7.734514,25.709440,...,25.033035,NaN,4.029433,28.644238,19.176878,21.325748,69.109764,13.387738,10.574944,NaN
2010-01-07,7.503227,34.195751,11.384212,39.970802,28.574459,30.260670,23.690254,26.398897,7.647105,25.718878,...,24.961973,NaN,3.977766,28.587803,19.373568,21.362940,68.380905,13.544745,10.542482,NaN
2010-01-08,7.624931,34.303909,11.496372,40.752888,28.507616,30.977947,23.922579,26.511236,7.671760,26.084042,...,25.129936,NaN,3.963005,28.330322,19.529278,21.386179,68.402977,14.074646,10.417631,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-12,9.569000,136.199997,112.099998,23.760000,49.615002,52.680000,16.209999,171.899994,27.025000,97.379997,...,46.119999,13.770,36.500000,137.160004,223.500000,56.619999,50.799999,24.740000,8.912000,41.330002
2022-12-13,9.698000,138.199997,113.480003,24.240000,49.730000,53.630001,16.219999,174.699997,27.405001,97.449997,...,47.029999,13.802,37.750000,141.039993,224.899994,57.889999,52.700001,25.120001,8.936000,41.570000
2022-12-14,9.671000,138.160004,113.000000,23.980000,49.730000,53.509998,15.605000,172.350006,27.080000,95.480003,...,47.000000,13.890,37.224998,139.500000,226.500000,57.480000,53.090000,25.389999,8.928000,40.910000
2022-12-15,9.346000,134.080002,110.680000,23.240000,48.625000,51.669998,15.815000,165.149994,26.215000,93.930000,...,45.235001,13.538,35.410000,132.779999,218.300003,56.430000,51.880001,24.299999,8.714000,38.139999
2022-12-16,9.384000,132.759995,109.980003,22.820000,48.625000,52.540001,15.575000,159.449997,26.030001,92.389999,...,44.610001,13.364,34.939999,130.820007,213.600006,55.660000,49.419998,24.230000,8.670000,37.070000

In [9]:
df.pct_change()

,ACA.PA,AI.PA,AIR.PA,ALO.PA,BN.PA,BNP.PA,CA.PA,CAP.PA,CS.PA,DG.PA,...,SGO.PA,STLA.PA,STM.PA,SU.PA,TEP.PA,TTE.PA,URW.AS,VIE.PA,VIV.PA,WLN.PA
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05,0.015205,-0.020000,-0.003217,0.002717,-0.008677,-0.001922,0.023676,0.012444,0.016667,0.007630,...,-0.004731,NaN,-0.000154,-0.004851,0.023542,0.001201,-0.001288,0.007709,-0.000234,NaN
2010-01-06,0.017665,-0.006158,0.008964,0.006001,-0.000117,0.001575,-0.007327,0.019843,0.010246,0.013778,...,-0.004240,NaN,0.011737,-0.010238,-0.012450,0.000654,0.008704,0.014662,-0.010745,NaN
2010-01-07,0.000377,-0.001215,0.009950,0.003079,-0.002101,0.017476,-0.011288,-0.010455,-0.011301,0.000367,...,-0.002839,NaN,-0.012822,-0.001970,0.010257,0.001744,-0.010546,0.011728,-0.003070,NaN
2010-01-08,0.016220,0.003163,0.009852,0.019566,-0.002339,0.023703,0.009807,0.004255,0.003224,0.014198,...,0.006729,NaN,-0.003711,-0.009007,0.008037,0.001088,0.000323,0.039122,-0.011843,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-12,0.001675,-0.004677,0.004120,-0.011647,-0.011850,-0.003970,-0.019062,-0.000291,-0.011883,-0.012574,...,-0.014530,0.000291,-0.009095,-0.008816,-0.005340,0.005862,-0.032197,-0.019421,-0.009778,0.004863
2022-12-13,0.013481,0.014684,0.012310,0.020202,0.002318,0.018033,0.000617,0.016289,0.014061,0.000719,...,0.019731,0.002324,0.034247,0.028288,0.006264,0.022430,0.037402,0.015360,0.002693,0.005807
2022-12-14,-0.002784,-0.000289,-0.004230,-0.010726,0.000000,-0.002238,-0.037916,-0.013452,-0.011859,-0.020215,...,-0.000638,0.006376,-0.013907,-0.010919,0.007114,-0.007082,0.007400,0.010748,-0.000895,-0.015877
2022-12-15,-0.033606,-0.029531,-0.020531,-0.030859,-0.022220,-0.034386,0.013457,-0.041776,-0.031942,-0.016234,...,-0.037553,-0.025342,-0.048758,-0.048172,-0.036203,-0.018267,-0.022791,-0.042930,-0.023970,-0.067710
2022-12-16,0.004066,-0.009845,-0.006325,-0.018072,0.000000,0.016838,-0.015175,-0.034514,-0.007057,-0.016395,...,-0.013817,-0.012853,-0.013273,-0.014761,-0.021530,-0.013645,-0.047417,-0.002881,-0.005049,-0.028055